export const FETCH_USER="fetch_user"
export const AUTH_USER="auth_user"
export const AUTH_ERROR="auth_error"
export const FETCH_PRODUCT="fetch _product"
export const FETCH_PRODUCT_ERROR="product_error"
export const ADD_PRODUCT_ERROR="add_product_error"